# Generated by Django 3.0.3 on 2020-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_fr',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
