# Generated by Django 3.0.3 on 2020-02-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20200225_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon.Pokemon')),
            ],
        ),
    ]
