# Generated by Django 3.0.3 on 2020-02-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemonvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='pokemon.Pokemon'),
        ),
        migrations.DeleteModel(
            name='PokemonVariant',
        ),
    ]
