# Generated by Django 3.0.3 on 2020-02-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='pokemon.Region'),
        ),
    ]
