# Generated by Django 3.0.3 on 2020-02-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name_de',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name_kr',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
