# Generated by Django 3.0.3 on 2020-02-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20200229_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='region',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='pokemon.Generation'),
        ),
    ]
