# Generated by Django 3.0.3 on 2020-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_userpokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
