# Generated by Django 3.0.3 on 2020-03-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_auto_20200307_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='generation',
        ),
        migrations.CreateModel(
            name='PokemonRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=255)),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon.Pokemon')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon.Region')),
            ],
        ),
    ]
