# Generated by Django 3.0.3 on 2020-03-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonOptions',
            new_name='PokemonOption',
        ),
    ]
