# Generated by Django 3.0.3 on 2020-03-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userpokemonoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemonoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='userpokemonoption',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='userpokemonoption',
            name='user',
        ),
        migrations.DeleteModel(
            name='PokemonOption',
        ),
        migrations.DeleteModel(
            name='UserPokemonOption',
        ),
    ]
